assessment/urls.py
from django.urls import path

from . import views


app_name = 'assessment'
urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('inquiry/', views.InquiryView.as_view(), name="inquiry"),
    path('cardset-list/', views.CardSetListView.as_view(), name="cardset_list"),
    path('card-list/<title>/', views.CardListView.as_view(), name="card_list"),
    path('cardcomment-list/<cardName>/', views.CardCommentListView.as_view(), name="cardcomment_list"),
    path('cardcomment-detail/<int:pk>/', views.CardCommentDetailView.as_view(), name="cardcomment_detail"),
    path('cardcomment-create/', views.CardCommentCreateView.as_view(), name="cardcomment_create"),
    path('cardcomment-update/<int:pk>/', views.CardCommentUpdateView.as_view(), name="cardcomment_update"),
    path('cardcomment-delete/<int:pk>/', views.CardCommentDeleteView.as_view(), name="cardcomment_delete"),
]

mtg_assessment/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.urls import path, include

from . import settings_common, settings_dev

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('assessment.urls')),
    path('accounts/', include('allauth.urls')),
]

# 開発サーバーでメディアを配信できるようにする設定
urlpatterns += static(settings_common.MEDIA_URL, document_root=settings_dev.MEDIA_ROOT)

accounts/models.py
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    """拡張ユーザーモデル"""

    class Meta:
        verbose_name_plural = 'CustomUser'

assessment/models.py
from accounts.models import CustomUser
from django.db import models


class CardSet(models.Model):
    """カードセットモデル"""

    title = models.CharField(verbose_name='カードセット英字', max_length=100)
    cardSetName = models.CharField(verbose_name='カードセット名', max_length=100)

    class Meta:
        verbose_name_plural = 'CardSet'

    def __str__(self):
        return self.title

class Card(models.Model):
    """カードモデル"""

    cardSetTitle = models.ForeignKey(CardSet, verbose_name='カードセット英字', max_length=100, on_delete=models.PROTECT)
    cardName = models.CharField(verbose_name='カード名', max_length=100)

    class Meta:
        verbose_name_plural = 'Card'

    def __str__(self):
        return self.cardName

MARK = (
    ("◎", "◎"),
    ("○", "○"),
    ("△", "△"),
    ("×", "×"),
)

FORMAT = (
    ("スタンダード", "スタンダード"),
    ("パイオニア", "パイオニア"),
    ("モダン", "モダン"),
    ("レガシー", "レガシー"),
    ("ヴィンテージ", "ヴィンテージ"),
    ("パウパー", "パウパー"),
    ("ヒストリック", "ヒストリック"),
    ("統率者戦", "統率者戦"),
    ("シールド", "シールド"),
    ("ドラフト", "ドラフト"),
)

class CardComment(models.Model):
    """カードコメントモデル"""

    cardName = models.ForeignKey(Card, verbose_name='カード名', max_length=100, on_delete=models.PROTECT)
    mark = models.CharField(verbose_name='評価マーク', max_length=100, choices=MARK)
    format = models.CharField(verbose_name='フォーマット', max_length=100, choices=FORMAT)
    comment = models.TextField(verbose_name='コメント本文', max_length=100000)
    user = models.CharField(verbose_name='ユーザー', max_length=100000)
    created_at = models.DateTimeField(verbose_name='作成日時', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='更新日時', auto_now=True)

    class Meta:
        verbose_name_plural = 'CardComment'

    def __str__(self):
        return self.comment

assessment/forms.py
from django import forms
from django.core.mail import EmailMessage
from .models import CardComment


class InquiryForm(forms.Form):
    name = forms.CharField(label='お名前', max_length=30)
    email = forms.EmailField(label='メールアドレス')
    title = forms.CharField(label='タイトル', max_length=30)
    message = forms.CharField(label='メッセージ', widget=forms.Textarea)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['name'].widget.attrs['class'] = 'form-control col-9'
        self.fields['name'].widget.attrs['placeholder'] = 'お名前をここに入力してください。'

        self.fields['email'].widget.attrs['class'] = 'form-control col-11'
        self.fields['email'].widget.attrs['placeholder'] = 'メールアドレスをここに入力してください。'

        self.fields['title'].widget.attrs['class'] = 'form-control col-11'
        self.fields['title'].widget.attrs['placeholder'] = 'タイトルをここに入力してください。'

        self.fields['message'].widget.attrs['class'] = 'form-control col-12'
        self.fields['message'].widget.attrs['placeholder'] = 'メッセージをここに入力してください。'

    def send_email(self):
        name = self.cleaned_data['name']
        email = self.cleaned_data['email']
        title = self.cleaned_data['title']
        message = self.cleaned_data['message']

        subject = 'お問い合わせ {}'.format(title)
        message = '送信者名: {0}\nメールアドレス: {1}\nメッセージ:\n{2}'.format(name, email, message)
        from_email = 'admin@example.com'
        to_list = [
            'test@example.com'
        ]
        cc_list = [
            email
        ]

        message = EmailMessage(subject=subject, body=message, from_email=from_email, to=to_list, cc=cc_list)
        message.send()

class CardCommentCreateForm(forms.ModelForm):
    class Meta:
        model = CardComment
        fields = ('cardName', 'mark', 'format', 'comment', )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

accounts/views.py
from django.shortcuts import render

# Create your views here.

assessment/views.py
import logging

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from .forms import InquiryForm
from .forms import CardCommentCreateForm
from .models import CardSet
from .models import Card
from .models import CardComment

logger = logging.getLogger(__name__)


class IndexView(generic.TemplateView):
    model = CardComment
    template_name = "index.html"

    def get_context_data(self, **kwargs):
        cardcomment_list = CardComment.objects.all().order_by('-updated_at')
        cardcomment_dict = {'cardcomment_list': cardcomment_list}
        context = cardcomment_dict
        return context

class InquiryView(generic.FormView):
    template_name = "inquiry.html"
    form_class = InquiryForm
    success_url = reverse_lazy('assessment:inquiry')

    def form_valid(self, form):
        form.send_email()
        messages.success(self.request, 'メッセージを送信しました。')
        logger.info('Inquiry sent by {}'.format(form.cleaned_data['name']))
        return super().form_valid(form)


class CardSetListView(generic.ListView):
    model = CardSet
    template_name = 'cardset_list.html'
    paginate_by = 5
    slug_field = "title"
    slug_url_kwarg = "title"

class CardListView(generic.ListView):
    model = Card
    template_name = 'card_list.html'
    paginate_by = 10
    slug_field = "cardName"
    slug_url_kwarg = "cardName"

class CardCommentListView(generic.ListView):
    model = CardComment
    template_name = 'cardcomment_list.html'
    paginate_by = 10
    slug_field = "cardName"
    slug_url_kwarg = "cardName"

    def get_queryset(self):
        return super().get_queryset().order_by('-updated_at')

class CardCommentDetailView(generic.DetailView):
    model = CardComment
    template_name = 'cardcomment_detail.html'

class CardCommentCreateView(LoginRequiredMixin, generic.CreateView):
    model = CardComment
    template_name = 'cardcomment_create.html'
    form_class = CardCommentCreateForm
    success_url = reverse_lazy('assessment:cardset_list')

    def form_valid(self, form):
        cardcomment = form.save(commit=False)
        cardcomment.user = str(self.request.user)
        cardcomment.save()
        messages.success(self.request, 'コメントを投稿しました。')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "コメントの投稿に失敗しました。")
        return super().form_invalid(form)

class CardCommentUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = CardComment
    template_name = 'cardcomment_update.html'
    form_class = CardCommentCreateForm
    success_url = reverse_lazy('assessment:cardset_list')

    def form_valid(self, form):
        messages.success(self.request, 'コメントを更新しました。')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "コメントの更新に失敗しました。")
        return super().form_invalid(form)

class CardCommentDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = CardComment
    template_name = 'cardcomment_delete.html'
    success_url = reverse_lazy('assessment:cardset_list')

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, "コメントを削除しました。")
        return super().delete(request, *args, **kwargs)

assessment/templates/base.html
{% load static %}

<html lang="ja">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.css' %}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/one-page-wonder.css' %}" rel="stylesheet">

    <!-- My style -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/mystyle.css' %}">
    {% block head %}{% endblock %}
  </head>

  <body>
	<div id="wrapper">
        <!-- Navigation -->
        <nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
          <div class="container">
            <a class="navbar-brand" href="{% url 'assessment:index' %}">MTGカード評価投稿</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item {% block active_inquiry %}{% endblock %}">
                  <a class="nav-link" href="{% url 'assessment:inquiry' %}">INQUIRY</a>
                </li>

                  <li class="nav-item {% block active_cardset_list %}{% endblock %}">
                      <a class="nav-link" href="{% url 'assessment:cardset_list' %}">CARDSET LIST</a>
                  </li>

              </ul>
              <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                  <li class="nav-item">
                      <a class="nav-link" href="{% url 'account_logout' %}">Log Out</a>
                  </li>
                {% else %}
                  <li class="nav-item {% block active_signup %}{% endblock %}">
                      <a class="nav-link" href="{% url 'account_signup' %}">Sign Up</a>
                  </li>
                  <li class="nav-item {% block active_login %}{% endblock %}">
                      <a class="nav-link" href="{% url 'account_login' %}">Log In</a>
                  </li>
                {% endif %}
              </ul>
            </div>
          </div>
        </nav>

        {% block header%}{% endblock %}

        {% if messages %}
          <div class="container">
              <div class="row">
                  <div class="my-div-style w-100">
                      <ul class="messages" style="list-style: none;">
                          {% for message in messages %}
                          <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>
                              {{ message }}
                          </li>
                          {% endfor %}
                      </ul>
                  </div>
              </div>
          </div>
        {% endif %}

        {% block contents%}{% endblock %}

        <!-- Footer -->
        <footer class="py-5 bg-black">
          <div class="container">
            <p class="m-0 text-center text-white small">Copyright &copy; MTGカード評価投稿 2020</p>
          </div>
          <!-- /.container -->
        </footer>

        <!-- Bootstrap core JavaScript -->
        <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
        <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  	</div>
  </body>

</html>

assessment/templates/card_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}セット別カード一覧{% endblock %}

{% block active_card_list %}active{% endblock %}

{% block head %}
<link href="{% static 'css/clean-blog.min.css' %}" rel="stylesheet">
{% endblock %}

{% block contents %}
<div class="container">
    <div class="row">
        <div class="my-div-style w-100">
            <div class="col-lg-8 col-md-10 mx-auto">
                {% for card in card_list %}
                    {% if card.cardSetTitle|stringformat:"s" in request.path %}
                        <div class="post-preview">
                            <a href="{% url 'assessment:cardcomment_list' card.cardName %}">
                              <h2 class="post-title">
                                {{ card.cardName }}
                              </h2>
                            </a>
                        </div>
                     {% endif %}
                {% empty %}
                    <p>カードがありません。</p>
                {% endfor %}

                <!-- ページネーション処理 -->
                {% if is_paginated %}
                    <ul class="pagination">
                        <!-- 前ページへのリンク -->
                        {% if page_obj.has_previous %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                                    <span aria-hidden="true">&laquo;</span>
                                </a>
                            </li>
                        {% endif %}

                        <!-- ページ数表示 -->
                        {% for page_num in page_obj.paginator.page_range %}
                            {% if page_obj.number == page_num %}
                                <li class="page-item active"><a class="page-link" href="#">{{ page_num }}</a></li>
                            {% else %}
                                <li class="page-item"><a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a></li>
                            {% endif %}
                        {% endfor %}

                        <!-- 次ページへのリンク -->
                        {% if page_obj.has_next %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                                    <span aria-hidden="true">&raquo;</span>
                                </a>
                            </li>
                        {% endif %}
                    </ul>
                {% endif %}

            </div>
        </div>
    </div>
</div>
{% endblock %}

assessment/templates/cardcomment_create.html
{% extends 'base.html' %}
{% load static %}

{% block title %}カードコメント作成{% endblock %}

{% block active_cardcomment_list %}active{% endblock %}

{% block contents %}
<div class="container">
    <div class="row">
        <div class="my-div-style w-100">
            <form method="POST" enctype='multipart/form-data'>
                {% csrf_token %}
                <table class="table">
                    {{ form.as_table }}
                </table>
                <button class="btn btn-primary mt-5" type="submit">投稿</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

assessment/templates/cardcomment_delete.html
{% extends 'base.html' %}
{% load static %}

{% block title %}カードコメント削除{% endblock %}

{% block active_cardcomment_list %}active{% endblock %}

{% block contents %}
<div class="container">
    <div class="row">
        <div class="my-div-style w-100">
            <form method="POST">
                {% csrf_token %}
                <p>本当に削除しますか？</p>
                <button class="btn btn-primary mt-5" type="submit">削除</button>
                <a class="btn btn-secondary mt-5 ml-2" href="{% url 'assessment:cardcomment_detail' object.pk %}">キャンセル</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

assessment/templates/cardcomment_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}カード詳細{% endblock %}

{% block active_cardcomment_list %}active{% endblock %}


{% block contents %}
<div class="container">
    <div class="my-div-style w-100">
        <div class="row">
            <div class="col-3">
                <strong>カード名</strong>
            </div>
            <div class="col-9">
                {{ object.cardName }}
            </div>
        </div>

        <hr>

        <div class="row">
            <div class="col-3">
                <strong>評価マーク</strong>
            </div>
            <div class="col-9">
                {{ object.mark }}
            </div>
        </div>

        <hr>

        <div class="row">
            <div class="col-3">
                <strong>フォーマット</strong>
            </div>
            <div class="col-9">
                {{ object.format }}
            </div>
        </div>

        <hr>

        <div class="row">
            <div class="col-3">
                <strong>コメント</strong>
            </div>
            <div class="col-9">
                {{ object.comment|linebreaksbr }}
            </div>
        </div>

        <hr>

        <div class="row">
            <div class="col-3">
                <strong>ユーザー</strong>
            </div>
            <div class="col-9">
                {{ object.user }}
            </div>
        </div>

        <hr>

        <div class="row">
            <div class="col-3">
                <strong>作成日時</strong>
            </div>
            <div class="col-9">
                {{ object.created_at }}
            </div>
        </div>

        <hr>

        <div class="row">
            <div class="col-3">
                <strong>更新日時</strong>
            </div>
            <div class="col-9">
                {{ object.updated_at }}
            </div>
        </div>

        {% if user.is_authenticated %}
            {% ifequal user|stringformat:"s" object.user|stringformat:"s" %}
                <a class="btn btn-success mt-5 mb-3" href="{% url 'assessment:cardcomment_update' object.pk %}">編集</a>
                <a class="btn btn-danger mt-5 ml-2 mb-3" href="{% url 'assessment:cardcomment_delete' object.pk %}">削除</a>
           {% endifequal %}
        {% endif %}

    </div>
</div>
{% endblock %}

assessment/templates/cardcomment_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}セット別カード一覧{% endblock %}

{% block active_cardcomment_list %}active{% endblock %}

{% block head %}
<link href="{% static 'css/clean-blog.min.css' %}" rel="stylesheet">
{% endblock %}

{% block contents %}
<div class="container">
    <div class="row">
        <div class="my-div-style w-100">
            <div class="col-lg-8 col-md-10 mx-auto">
                <div class="clearfix">
                    {% if user.is_authenticated %}
                        <a class="btn btn-primary float-right" href="{% url 'assessment:cardcomment_create' %}">新規作成</a>
                    {% endif %}
                </div>
                <h2 class="post-title">
                    カード別コメント一覧
                </h2>
                <br>
                {% for cardcomment in cardcomment_list %}
                    {% if cardcomment.cardName|stringformat:"s" in request.path %}
                        <div class="post-preview">
                            <a href="{% url 'assessment:cardcomment_detail' cardcomment.pk %}">
                                <h5>{{ cardcomment.cardName }}</h5>
                                {% if cardcomment.mark == "◎" %}
                                    <font color="blue">
                                {% elif  cardcomment.mark == "○" %}
                                    <font color="green">
                                {% elif  cardcomment.mark == "△" %}
                                    <font color="orange">
                                {% else %}
                                    <font color="red">
                                {% endif %}
                                        {{ cardcomment.mark|truncatechars:20 }}
                                    </font>
                                <b>{{ cardcomment.format|truncatechars:20 }}</b><br>
                                {{ cardcomment.comment|truncatechars:20 }}<br>
                            </a>
                            <p class="post-meta">更新日時：{{ cardcomment.updated_at }}</p>
                            <hr>
                        </div>
                     {% endif %}
                {% empty %}
                    <p>コメントがありません。</p>
                {% endfor %}

                <!-- ページネーション処理 -->
                {% if is_paginated %}
                    <ul class="pagination">
                        <!-- 前ページへのリンク -->
                        {% if page_obj.has_previous %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                                    <span aria-hidden="true">&laquo;</span>
                                </a>
                            </li>
                        {% endif %}

                        <!-- ページ数表示 -->
                        {% for page_num in page_obj.paginator.page_range %}
                            {% if page_obj.number == page_num %}
                                <li class="page-item active"><a class="page-link" href="#">{{ page_num }}</a></li>
                            {% else %}
                                <li class="page-item"><a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a></li>
                            {% endif %}
                        {% endfor %}

                        <!-- 次ページへのリンク -->
                        {% if page_obj.has_next %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                                    <span aria-hidden="true">&raquo;</span>
                                </a>
                            </li>
                        {% endif %}
                    </ul>
                {% endif %}

            </div>
        </div>
    </div>
</div>
{% endblock %}

assessment/templates/cardcomment_update.html
{% extends 'base.html' %}
{% load static %}

{% block title %}カードコメント更新{% endblock %}

{% block active_cardcomment_list %}active{% endblock %}

{% block contents %}
<div class="container">
    <div class="row">
        <div class="my-div-style w-100">
            <form method="POST" enctype='multipart/form-data'>
                {% csrf_token %}
                <table class="table">
                    {{ form.as_table }}
                </table>
                <button class="btn btn-primary" type="submit">更新</button>
                <a class="btn btn-secondary ml-2" href="{% url 'assessment:cardcomment_detail' object.pk %}">キャンセル</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

assessment/templates/cardset_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}カードセット一覧{% endblock %}

{% block active_cardset_list %}active{% endblock %}

{% block head %}
<link href="{% static 'css/clean-blog.min.css' %}" rel="stylesheet">
{% endblock %}

{% block contents %}
<div class="container">
    <div class="row">
        <div class="my-div-style w-100">
            <div class="col-lg-8 col-md-10 mx-auto">
                {% for cardset in cardset_list %}
                    <div class="post-preview">
                        <a href="{% url 'assessment:card_list' cardset.title %}">
                          <h2 class="post-title">
                            {{ cardset.cardSetName }}
                          </h2>
                        </a>
                    </div>
                {% empty %}
                    <p>カードセットがありません。</p>
                {% endfor %}

                <!-- ページネーション処理 -->
                {% if is_paginated %}
                    <ul class="pagination">
                        <!-- 前ページへのリンク -->
                        {% if page_obj.has_previous %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                                    <span aria-hidden="true">&laquo;</span>
                                </a>
                            </li>
                        {% endif %}

                        <!-- ページ数表示 -->
                        {% for page_num in page_obj.paginator.page_range %}
                            {% if page_obj.number == page_num %}
                                <li class="page-item active"><a class="page-link" href="#">{{ page_num }}</a></li>
                            {% else %}
                                <li class="page-item"><a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a></li>
                            {% endif %}
                        {% endfor %}

                        <!-- 次ページへのリンク -->
                        {% if page_obj.has_next %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                                    <span aria-hidden="true">&raquo;</span>
                                </a>
                            </li>
                        {% endif %}
                    </ul>
                {% endif %}

            </div>
        </div>
    </div>
</div>
{% endblock %}

assessment/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}MTGカード評価投稿サイト{% endblock %}

{% block active_cardcomment_list %}active{% endblock %}

{% block header%}
<header class="masthead text-center text-white">
  <div class="masthead-content">
    <div class="container">
      <h1 class="masthead-heading mb-0">MTGカード評価投稿</h1>
      <h2 class="masthead-subheading mb-0">トレーディングカードゲーム「Magic：The Gathering(MTG)」のカード評価を投稿するサイトです</h2>
      <a href="{% url 'account_login' %}" class="btn btn-primary btn-xl rounded-pill mt-5">LOG IN</a>
    </div>
  </div>
  <div class="bg-circle-1 bg-circle"></div>
  <div class="bg-circle-2 bg-circle"></div>
  <div class="bg-circle-3 bg-circle"></div>
  <div class="bg-circle-4 bg-circle"></div>
</header>
{% endblock %}

{% block head %}
    <!-- Custom styles for this template -->
    <link href="{% static 'css/one-page-wonder.css' %}" rel="stylesheet">

    <!-- My style -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/mystyle.css' %}">
<link href="{% static 'css/clean-blog_index.css' %}" rel="stylesheet">
{% endblock %}

{% block contents %}
<br>
<section>
  <div class="container">
    <div class="row align-items-center">
            <div class="col-lg-8  mx-auto">
              <div class="clearfix">
                <h2 class="display-4">新着コメント</h2>
                {% for cardcomment in cardcomment_list|slice:":3" %}
                        <div class="post-preview">
                            <a href="{% url 'assessment:cardcomment_detail' cardcomment.pk %}">
                                <h5>{{ cardcomment.cardName }}</h5>
                                {% if cardcomment.mark == "◎" %}
                                    <font color="blue">
                                {% elif  cardcomment.mark == "○" %}
                                    <font color="green">
                                {% elif  cardcomment.mark == "△" %}
                                    <font color="orange">
                                {% else %}
                                    <font color="red">
                                {% endif %}
                                        {{ cardcomment.mark|truncatechars:20 }}
                                    </font>
                                <b>{{ cardcomment.format|truncatechars:20 }}</b><br>
                                {{ cardcomment.comment|truncatechars:20 }}<br>
                            </a>
                            <p class="post-meta">更新日時：{{ cardcomment.updated_at }}</p>
                            <hr>
                        </div>
                {% empty %}
                    <p>コメントがありません。</p>
                {% endfor %}
              </div>
        </div>
    </div>
  </div>
</section>
{% endblock %}

assessment/templates/inquiry.html
{% extends 'base.html' %}

{% block title %}お問い合わせ{% endblock %}

{% block active_inquiry %}active{% endblock %}

{% block contents %}
<div class="container">
    <div class="row">
        <div class="my-div-style">
            <form method="post">
                {% csrf_token %}

                {{ form.non_field_errors }}

                {% for field in form %}
                    <div class="form-group row">
                        <label for="{{ field.id_for_label }}" class="col-sm-4 col-form-label">
                            <strong>{{ field.label_tag }}</strong>
                        </label>
                        <div class="col-sm-8">
                            {{ field }}
                            {{ field.errors }}
                        </div>
                    </div>
                {% endfor %}

                <div class="offset-sm-4 col-sm-8">
                    <button class="btn btn-primary mt-5" type="submit">送信</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}